# Generated by Django 6.0.3 on 2026-04-12 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0004_sellrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellrequest',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sell.variant'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='sell.device'),
        ),
    ]
