# Generated by Django 6.0.3 on 2026-04-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0005_sellrequest_variant_alter_variant_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pickup', 'Pickup Scheduled'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
    ]
