# Generated by Django 6.0.3 on 2026-04-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('phone', 'Phone'), ('laptop', 'Laptop'), ('accessory', 'Accessory')], default='phone', max_length=50),
        ),
    ]
