# Generated by Django 6.0.3 on 2026-04-09 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_old_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='condition',
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('Fair', 'Fair'), ('Good', 'Good'), ('Superb', 'Superb')], max_length=50)),
                ('storage', models.CharField(choices=[('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('512GB', '512GB')], max_length=50)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
        ),
    ]
